---
- name: Restart Wazuh manager
  listen: restart wazuh-manager
  ansible.builtin.systemd:
    name: wazuh-manager
    state: restarted
    daemon_reload: true
  become: true

- name: Restart Filebeat
  listen: restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    daemon_reload: true
  become: true
