"""Generate Ansible route projections from compiled service manifests."""

from __future__ import annotations

from typing import TYPE_CHECKING

import yaml

from toolkit.core.manifest.routes import compile_routes

if TYPE_CHECKING:
    from toolkit.core.config.config import Config


def build_route_group_vars(cfg: Config) -> dict:
    """Project compiled public/private routes into Ansible host variables."""
    hosts = {node_id: machine.hostname for node_id, machine in cfg.machines.items() if machine.enabled}
    published: dict[str, set[str]] = {host: set() for host in hosts.values()}
    private: dict[str, set[str]] = {host: set() for host in hosts.values()}
    expected: dict[str, set[str]] = {host: set() for host in hosts.values()}

    for route in compile_routes(cfg):
        try:
            host = hosts[route.node]
        except KeyError as exc:
            raise ValueError(f"route {route.service!r} targets unavailable node {route.node!r}") from exc
        if route.exposure == "public":
            if route.subdomain:
                published[host].add(route.subdomain)
            expected[host].add(f"https://{route.host}")
        elif route.subdomain:
            private[host].add(route.subdomain)

    from toolkit.core.ops.dns import external_host_fqdn

    external_rewrites = {
        external_host_fqdn(host.name, cfg.domain): host.ip for host in getattr(cfg, "external_hosts", None) or []
    }
    return {
        "published_subdomains": {host: sorted(values) for host, values in published.items() if values},
        "private_subdomains": {host: sorted(values) for host, values in private.items() if values},
        "expected_urls": {host: sorted(values) for host, values in expected.items() if values},
        "external_hosts_rewrites": external_rewrites,
    }


def render_ansible_routes_yml(cfg: Config) -> str:
    data = build_route_group_vars(cfg)
    header = (
        "# AUTO-GENERATED BY toolkit.core.ansible.ansible_routes "
        "(run via homelab-toolkit generate)\n"
        "# Included by Ansible inventory generation.\n\n"
    )
    return header + yaml.dump(data, default_flow_style=False, sort_keys=False)
