"""Generate OpenTofu and Ansible files from root config.yaml."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml

from toolkit.core.config.config import Config
from toolkit.core.config.storage import DEFAULT_HOMELAB_ROOT


def load_config_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text()) or {}
    return data if isinstance(data, dict) else {}


def _hcl_string(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _hcl_key(value: object) -> str:
    text = str(value)
    return text if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", text) else _hcl_string(text)


def _hcl_assignments(items: list[tuple[object, Any]], *, indent: int = 0) -> list[str]:
    rendered = [(_hcl_key(key), _hcl_value(value, indent=indent)) for key, value in items]
    prefix = " " * indent
    lines: list[str] = []
    scalar_group: list[tuple[str, str]] = []

    def flush_scalars() -> None:
        width = max((len(key) for key, _value in scalar_group), default=0)
        lines.extend(f"{prefix}{key.ljust(width)} = {value}" for key, value in scalar_group)
        scalar_group.clear()

    for key, value in rendered:
        if "\n" in value:
            flush_scalars()
            lines.append(f"{prefix}{key} = {value}")
        else:
            scalar_group.append((key, value))
    flush_scalars()
    return lines


def _hcl_value(value: Any, *, indent: int = 0) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return _hcl_string(value)
    if isinstance(value, int | float):
        return str(value)
    if isinstance(value, list | tuple):
        if not value:
            return "[]"
        inner = ",\n".join(f"{' ' * (indent + 2)}{_hcl_value(item, indent=indent + 2)}" for item in value)
        return f"[\n{inner}\n{' ' * indent}]"
    if isinstance(value, dict):
        if not value:
            return "{}"
        lines = _hcl_assignments(list(value.items()), indent=indent + 2)
        return "{\n" + "\n".join(lines) + f"\n{' ' * indent}}}"
    raise TypeError(f"unsupported HCL value: {type(value).__name__}")


def render_generated_tfvars(
    raw: dict[str, Any],
) -> str:
    """Build HCL body for infrastructure/generated.auto.tfvars (BPG provider / LXC)."""
    cfg = Config.model_validate(raw)
    api_url = cfg.proxmox.api_url
    # BPG provider expects the base Proxmox URL (no /api2/json suffix).
    api_url = re.sub(r"/api2/json/?$", "/", api_url)

    ssh_key = cfg.proxmox.ssh_public_key
    if not ssh_key or "REPLACE_WITH_YOUR" in ssh_key:
        raise ValueError("proxmox.ssh_public_key is required. Set it in config.local.yaml or through the setup UI.")
    machines: dict[str, dict[str, Any]] = {}
    for machine_id, machine in cfg.machines.items():
        spec = machine.model_dump(mode="json")
        spec.pop("provider", None)
        machines[machine_id] = spec

    config_lines = _hcl_assignments(
        [
            ("proxmox_api_url", api_url),
            ("proxmox_node", cfg.proxmox.node),
            ("ssh_public_key", ssh_key),
            ("lxc_template_url", cfg.proxmox.lxc_template_url),
            ("lxc_template_checksum", cfg.proxmox.lxc_template_checksum),
            ("lxc_template_datastore", cfg.proxmox.lxc_template_datastore),
            ("default_datastore", cfg.proxmox.lxc_storage),
        ]
    )
    lines = [
        "# AUTO-GENERATED BY toolkit.core.iac_sync (run via homelab-toolkit generate)",
        "# Do not edit manually. Edit config.yaml instead.",
        "",
        *config_lines,
        "",
        f"machines = {_hcl_value(machines)}",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_ansible_generated_yml(
    raw: dict[str, Any],
    *,
    repo_root: Path | None = None,
) -> str:
    from toolkit.core.manifest.variables import domain_to_base_dn

    cfg = Config.model_validate(raw)
    domain = cfg.domain
    from toolkit.core.manifest.catalog import load_service_catalog

    catalog = load_service_catalog(repo_root)
    from toolkit.core.manifest.artifacts import compile_config_sources, compile_generated_artifacts
    from toolkit.core.manifest.placement import service_node_map
    from toolkit.core.manifest.routes import compile_routes, service_is_enabled
    from toolkit.core.manifest.variables import compile_manifest_host_sources

    service_nodes = service_node_map(cfg, catalog)
    grouped_artifacts: dict[str, dict[str, Any]] = {}
    for artifact in compile_generated_artifacts(cfg, catalog, root=repo_root):
        record = grouped_artifacts.setdefault(
            artifact.path,
            {
                "path": artifact.path,
                "service": artifact.service,
                "nodes": [],
                "enabled": artifact.enabled,
                "kind": artifact.kind,
                "mode": artifact.mode,
                "sensitive": artifact.sensitive,
                "host_uid": artifact.host_uid,
                "host_gid": artifact.host_gid,
            },
        )
        record["nodes"].append(artifact.node)
    service_generated_artifacts = [
        {**record, "nodes": sorted(set(record["nodes"]))} for record in grouped_artifacts.values()
    ]
    service_config_sources = [
        source.as_ansible_vars() for source in compile_config_sources(cfg, catalog, root=repo_root)
    ]
    from toolkit.core.manifest.ownership import current_ownership, ownership_tombstones

    removed_machine_ids = (
        list(ownership_tombstones(repo_root, current_ownership(cfg, catalog)).machines) if repo_root is not None else []
    )
    service_ips = {
        service: cfg.machines[machine].address
        for service, machine in service_nodes.items()
        if machine in cfg.machines and cfg.machines[machine].enabled
    }
    service_host_sources = {
        manifest.name: compile_manifest_host_sources(cfg, manifest, DEFAULT_HOMELAB_ROOT, catalog=catalog)
        for manifest in catalog.manifests
    }
    service_route_hosts: dict[str, str] = {}
    for route in compile_routes(cfg, catalog):
        if route.match is None:
            service_route_hosts.setdefault(route.service, route.host)

    def service_task_files(phase: str) -> list[str]:
        """Return enabled service-owned Ansible task files for one lifecycle phase.

        Service folders may opt into host automation by adding a file under
        ``toolkit/services/<name>/ansible/<phase>.yml``.  The generated list is
        the only bridge the core playbooks need; service names and task paths do
        not have to be hardcoded in Ansible.
        """
        if repo_root is None:
            return []
        root = repo_root.resolve()
        entries: list[tuple[int, str, str]] = []
        for manifest in catalog.manifests:
            # Host files are also projected for disabled services so their
            # cleanup branch can remove stale units. Other phases are strictly
            # enabled-service work and must not mutate disabled services.
            if phase not in {"host", "cleanup"} and not service_is_enabled(cfg, manifest, catalog):
                continue
            candidate = root / "toolkit" / "services" / manifest.name / "ansible" / f"{phase}.yml"
            if candidate.is_file():
                phase_order = {
                    "guest": manifest.guest_task_order,
                    "recovery": manifest.recovery_task_order,
                }.get(phase, 1_000)
                entries.append(
                    (
                        phase_order,
                        manifest.name,
                        candidate.relative_to(root).as_posix(),
                    )
                )
        return [path for _order, _name, path in sorted(entries)]

    control_node = cfg.control_node
    control_ip = cfg.node_ip(control_node)
    from toolkit.core.registry.mesh import mesh_lan_cidr

    private_network = mesh_lan_cidr(cfg)

    def service_location(service: str) -> tuple[str, str]:
        machine = service_nodes[service]
        return machine, cfg.machines[machine].address

    ingress_service = catalog.require_provider("ingress").name
    ingress_node, ingress_ip = service_location(ingress_service)
    mesh_router_service = catalog.require_provider("mesh-router").name
    mesh_router_node, mesh_router_ip = service_location(mesh_router_service)
    tunnel_device_service = catalog.require_provider("tunnel-device").name
    vpn_node, vpn_node_ip = service_location(tunnel_device_service)
    dns_provider = catalog.provider("dns")
    dns_service = dns_provider.name if dns_provider else ""
    dns_service_ip = service_ips.get(dns_service, "")
    registry_provider = catalog.provider("registry-mirror")
    registry_service = registry_provider.name if registry_provider else ""
    registry_service_ip = service_ips.get(registry_service, "")
    registry_service_node = service_nodes.get(registry_service, "")
    # A capability provider owns its listener declaration.  The registry
    # capability currently has one listener; resolve it from that declaration
    # instead of coupling the core to a service-specific listener identifier.
    registry_listener = (
        registry_provider.network_listeners[0] if registry_provider and registry_provider.network_listeners else None
    )
    registry_port = registry_listener.port if registry_listener else 0
    registry_enabled = bool(
        registry_provider
        and service_is_enabled(cfg, registry_provider, catalog)
        and registry_service_ip
        and registry_service_node
        and registry_port
    )
    data: dict[str, Any] = {
        "base_domain": domain,
        "lldap_base_dn": domain_to_base_dn(domain),
        "proxmox_control_host": cfg.proxmox.resolved_control_host,
        "proxmox_node": cfg.proxmox.node,
        "zfs_proxmox_id": cfg.proxmox.lxc_storage,
        "proxmox_private_network": private_network,
        "private_network": private_network,
        "proxmox_private_gateway": cfg.machines[mesh_router_node].gateway,
        "proxmox_private_bridge_name": cfg.machines[mesh_router_node].private_bridge,
        "proxmox_private_bridge_cidr": (
            f"{cfg.machines[mesh_router_node].gateway}/{cfg.machines[mesh_router_node].cidr}"
        ),
        "proxmox_public_bridge_name": cfg.machines[mesh_router_node].public_bridge,
        "mesh_cidr": cfg.network.mesh_ipv4_cidr,
        "proxmox_private_network_enabled": cfg.proxmox.provision_machines,
        "repo_dest": DEFAULT_HOMELAB_ROOT,
        "homelab_timezone": cfg.timezone,
        "admin_email": cfg.email or f"admin@{domain}",
        "machine_ids": {machine_id: machine.vmid for machine_id, machine in cfg.machines.items()},
        "machine_ips": {machine_id: machine.address for machine_id, machine in cfg.machines.items()},
        "machine_kinds": {machine_id: machine.kind for machine_id, machine in cfg.machines.items()},
        "machine_data_mounts": {
            machine_id: [disk.path for disk in machine.data_disks] for machine_id, machine in cfg.machines.items()
        },
        "machine_specs": {
            machine_id: {
                "kind": machine.kind,
                "vmid": machine.vmid,
                "address": machine.address,
                "ssh_port": machine.ssh_port,
                "nesting": machine.nesting,
                "keyctl": machine.keyctl,
                "fuse": machine.fuse,
            }
            for machine_id, machine in cfg.machines.items()
            if machine.enabled and machine.managed
        },
        "removed_machine_ids": removed_machine_ids,
        "control_node": control_node,
        "control_ip": control_ip,
        "service_nodes": service_nodes,
        "service_generated_artifacts": service_generated_artifacts,
        "service_config_sources": service_config_sources,
        "service_ips": service_ips,
        "service_host_sources": service_host_sources,
        "service_route_hosts": service_route_hosts,
        "service_host_task_files": service_task_files("host"),
        "service_cleanup_task_files": service_task_files("cleanup"),
        "service_guest_task_files": service_task_files("guest"),
        "service_guest_final_task_files": service_task_files("guest-final"),
        "service_manager_task_files": service_task_files("manager"),
        "service_pre_deploy_task_files": service_task_files("pre-deploy"),
        "service_post_deploy_task_files": service_task_files("post-deploy"),
        "service_recovery_task_files": service_task_files("recovery"),
        "service_security_task_files": service_task_files("security"),
        "service_sync_task_files": service_task_files("sync"),
        "service_storage_task_files": service_task_files("storage"),
        "ingress_node": ingress_node,
        "ingress_ip": ingress_ip,
        "mesh_router_node": mesh_router_node,
        "mesh_router_ip": mesh_router_ip,
        "mesh_router_vmid": cfg.machines[mesh_router_node].vmid,
        "mesh_router_kind": cfg.machines[mesh_router_node].kind,
        "vpn_node": vpn_node,
        "vpn_node_ip": vpn_node_ip,
        "vpn_node_vmid": cfg.machines[vpn_node].vmid,
        "vpn_node_kind": cfg.machines[vpn_node].kind,
        "dns_service": dns_service,
        "dns_service_ip": dns_service_ip,
        "docker_dns_servers": ([dns_service_ip] if dns_service_ip else []) + ["1.1.1.1"],
        "registry_mirror_enabled": registry_enabled,
        "registry_mirror_service": registry_service,
        "registry_mirror_node": registry_service_node,
        "registry_mirror_ip": registry_service_ip,
        "registry_mirror_port": registry_port,
        "registry_mirror_url": (f"http://{registry_service_ip}:{registry_port}" if registry_enabled else ""),
    }

    from toolkit.core.manifest.settings import service_enabled

    data["vpn_enabled"] = service_enabled(cfg, tunnel_device_service)
    from toolkit.core.manifest.settings import service_setting_bool, service_setting_int

    data["homelab_rightsize_enabled"] = service_setting_bool(cfg, "homelab-ui", "rightsize-enabled")
    data["homelab_rightsize_interval_hours"] = service_setting_int(
        cfg,
        "homelab-ui",
        "rightsize-interval-hours",
    )

    internet_ingress = cfg.network.expose_via_internet
    data["internet_ingress_enabled"] = internet_ingress
    from toolkit.core.manifest.networking import compile_network_listeners

    public_listener_forwards = [
        {
            "service": listener.service,
            "id": listener.listener_id,
            "target_ip": cfg.node_ip(target_node),
            "port": listener.port,
            "protocol": listener.protocol,
        }
        for listener in compile_network_listeners(cfg, catalog)
        if "any" in listener.sources
        for target_node in listener.target_nodes
    ]
    data["public_listener_forwards"] = sorted(
        public_listener_forwards,
        key=lambda item: (item["service"], item["port"], item["protocol"], item["id"]),
    )

    data["homelab_backups_enabled"] = cfg.backups.enabled
    if cfg.backups.enabled and cfg.backups.target == "remote" and repo_root is not None:
        from toolkit.core.ops.backup_ssh import ensure_backup_ssh_identity

        data["kopia_backup_public_key"] = ensure_backup_ssh_identity(repo_root).public_key

    data["homelab_maintenance_enabled"] = cfg.maintenance.enabled
    data["homelab_maintenance_calendar"] = f"*-*-* {cfg.maintenance.daily_at}:00"
    data["mesh_subnet_router"] = cfg.fleet.mesh_subnet_router

    # The mesh TUN setup follows the provider manifest, not the whole
    # security category. A security service can be disabled independently.
    data["mesh_enabled"] = service_is_enabled(cfg, catalog.require_provider("mesh-router"), catalog)
    from toolkit.core.infra.network_policy import build_guest_firewall_policy, declared_service_ports

    data["homelab_firewall_rules"] = build_guest_firewall_policy(
        repo_root or Path("/__homelab_no_services__"),
        cfg.model_dump(mode="python"),
    )
    service_ports = declared_service_ports(repo_root, cfg) if repo_root is not None else {}
    data["homelab_published_ports"] = [
        {
            "roles": [node],
            "port": port,
            "proto": protocol,
            "service": service,
        }
        for node, entries in sorted(service_ports.items())
        for service, port, protocol in entries
    ]

    data["zfs_enabled"] = cfg.storage.zfs_enabled
    if cfg.storage.zfs_pool:
        data["zfs_pool"] = cfg.storage.zfs_pool
    if cfg.storage.zfs_disk_list:
        data["zfs_disk_list"] = cfg.storage.zfs_disk_list

    header = (
        "# AUTO-GENERATED BY toolkit.core.iac_sync "
        "(run via homelab-toolkit generate)\n"
        "# Do not edit manually. Edit config.yaml instead.\n\n"
    )
    return header + yaml.dump(
        data,
        default_flow_style=False,
        sort_keys=False,
    )


def sync_from_repo_root(repo_root: Path, *, dry_run: bool = False) -> tuple[Path, Path]:
    """Read config.yaml under repo_root; write tfvars and ansible generated.yml."""
    config_path = repo_root / "config.yaml"
    local_path = repo_root / "config.local.yaml"
    tfvars_out = repo_root / "infrastructure" / "generated.auto.tfvars"
    ansible_out = repo_root / "automation" / "ansible" / "group_vars" / "generated.yml"
    routes_out = repo_root / "automation" / "ansible" / "group_vars" / "generated-routes.yml"

    raw = load_config_yaml(config_path)
    # Merge config.local.yaml overlay (gitignored sensitive overrides)
    if local_path.exists():
        local_raw = load_config_yaml(local_path)
        from toolkit.core.config.config import _deep_merge

        raw = _deep_merge(raw, local_raw)
    cfg = Config.model_validate(raw)
    if "PROXMOX_IP" in cfg.proxmox.api_url:
        raise ValueError(
            "proxmox_api_url is still the default placeholder containing 'PROXMOX_IP'. "
            "Set proxmox.api_url in config.yaml to a valid Proxmox API URL."
        )

    tfvars_body = render_generated_tfvars(raw)
    ansible_body = render_ansible_generated_yml(raw, repo_root=repo_root)

    from toolkit.core.ansible.ansible_routes import render_ansible_routes_yml

    routes_body = render_ansible_routes_yml(cfg)

    if not dry_run:
        from toolkit.core.deploy.destructive_guard import write_sensitive_file

        tfvars_out.parent.mkdir(parents=True, exist_ok=True)
        write_sensitive_file(tfvars_out, tfvars_body)
        ansible_out.parent.mkdir(parents=True, exist_ok=True)
        write_sensitive_file(ansible_out, ansible_body)
        write_sensitive_file(routes_out, routes_body)
        _write_terraform_tfvars_secrets(repo_root)

    return tfvars_out, ansible_out


def _write_terraform_tfvars_secrets(repo_root: Path) -> None:
    """Write gitignored terraform.tfvars with Proxmox API token from secrets."""
    from toolkit.core.config.storage import secrets_path
    from toolkit.core.secrets.secrets import load_secrets_plaintext

    secrets = load_secrets_plaintext(secrets_path(repo_root))
    token_id = secrets.get("PROXMOX_API_TOKEN_ID", "").strip()
    token_secret = secrets.get("PROXMOX_API_TOKEN_SECRET", "").strip()
    if not token_id or not token_secret:
        return
    out = repo_root / "infrastructure" / "terraform.tfvars"
    body = f'# AUTO-GENERATED from secrets — do not commit\nproxmox_api_token = "{token_id}={token_secret}"\n'
    from toolkit.core.deploy.destructive_guard import write_sensitive_file

    write_sensitive_file(out, body)
